### PR TITLE
Added Awesome Curations + 1 New Book

### PR DESCRIPTION
**Pull request by s0md3v**

### CODE REVIEW

**Review by DoGByTe-ZN — CHANGES_REQUESTED** [review]
I really appreciate your additions to the GitHub Repo. The [Awesome Curation] resources are EPIC. Please could you remove the *Stealing your network* from your pull request as i do not want to be sharing illegally shared books from hard working InfoSec Authors.

**Review by DoGByTe-ZN — COMMENTED** [review]
Thanks for your commit, Please feel free to provide updates any time you wish! I really appreciate it man.

**Comment by s0md3v** [comment]
Ah sorry.
Not everyone is a jerk like me. I won't include _illegal_ content next time.
And I am more than happy to contribute here.
Sorry for not responding to your request, I was not on my pc.

**Comment by DoGByTe-ZN** [comment]
No problem at all man!

Its amazing how one simple LinkedIn Tagged Post can create such collaboration, thank you once more. Feel free to submit a pull request any time you want ;)

Cheers
Chelin

**Pull request merged**
